### ISSUE TITLE
BHOP  Glitch

### ISSUE THREAD

**Issue by peyman47** [PilgrimMites/AHK-Multi-Script#1]
hi
after while used bhop  dosent work  correctly
this code works good for me:
;--------------------------------Bhop--------------------------------
*space::
Loop
{
GetKeyState,state,space,P
If state = U
break

Send,{space}
Sleep,20
}
return
;--------------------------------end--------------------------------

**Comment by PilgrimMites** [comment]
Bhop works as intended. Everything is Humanized. I will be adding an option for perfect bhop that will be close to this.
